### ISSUE TITLE
tesuto

### ISSUE THREAD

**Issue by Yuta-Hachino** [Eight-Sion/CertificationServer#10]
```yaml
start_date: 2021/9/18
due_date: 2021/9/19
progress: 0.86
parent: 0
```
